### ISSUE TITLE
No result with filter for category Culture and Religion / Tourism

### ISSUE THREAD

**Issue by lmagreault** [plepe/openstreetbrowser-categories-main#54]
No result with filter for category Culture and Religion / Tourism.

Example : 
https://www.openstreetbrowser.org/#map=15/46.6769/5.5584&categories=tourism_attractions%5Btype%3Dartwork%5D

**Comment by plepe** [comment]
Thanks for notifying! Fixed in c96047e2925743bd06b2a9764b77fd037b21a510.

**Comment by plepe** [comment]
By the way, most of the cultural features in the region do not have an image yet (or - preferably - a corresponding wikidata item). Check: https://www.openstreetbrowser.org/#map=15/46.6769/5.5584&categories=culture-media

Read the 🛈 of the category for more information. If it is incomprehensible, please say so, so that I can improve the text.
