### ISSUE TITLE
Category idea: towers

### ISSUE THREAD

**Issue by matthewbauer** [plepe/openstreetbrowser-categories-main#72]
Can basically include any tower types (man_made=tower), but specifically I am interested in cellular towers (tower:type=communication).

**Comment by plepe** [comment]
Not sure, how this would fit into the categories structure. I would actually include it in the Infrastructure -> Buildings category.

I would suggest creating a custom category for this. As code, the following would suffice (14 is the minimum zoom level):

```yaml
query:
  14: nwr[man_made=tower]
```

To only show communication towers, you have to quote the tower:type because of the colon, so:

```yaml
query:
  14: nwr[man_made=tower]["tower:type"=communication]
```

To learn more about custom categories, check [the tutorial](https://github.com/plepe/OpenStreetBrowser/blob/master/doc/Tutorial.md)

Do you think this suffices? Or shall I create a category in the main categories for this?

**Comment by matthewbauer** [comment]
Yep that works as a customer category!
